.TH "mm6dread" "1" "0.3" "Pozsár Zsolt" "Status reader program for MM6D device"
.SH "NAME"
.LP 
MM6DRead \- Status reader program for MM6D device
.SH "SYNTAX"
.LP
\fBmm6dread\fP [-h | --help | -v | --version]
.br 
.SH "OPTIONS"
.TP
.B \-h \-\-help
Write useable parameters.
.TP
.B \-v \-\-version
Write version and build information.
.br
.SH "DESCRIPTION"
.LP 
You can check status of MM6D growing house controllers with this
software via network.
.br
This program is free software: you can redistribute it and/or modify it
under the terms of the European Union Public License 1.1 version.
.br
.SH "FILE"
.TP
\fI~/.config/mm6dread/mm6dread.ini\fR
configuration file
.TP
.br
.SH "AUTHOR"
Pozsár Zsolt \fIpozsar.zsolt@szerafingomba.hu\fR
